Add a folder of outputs to acro
AI-SDC/ACRO pull request #130
Opened 2023-08-06 14:01 UTC by mahaalbashir

Create a function that:
1. Takes a folder from the user and adds each file in that folder to an acro object as a custom output.
2.  Rename the outputs from numbers (output_0, output_1,..) to the name of the files.
3. Call "finalise" to create the SDC files (config.json, checksums, results.json).

2023-08-06 14:53 UTC, mahaalbashir commented
@rpreen I would like your advice on something, please.
The case:
If the user calls the add_to_acro function twice. For example: if the user calls it first then adds other files and calls it again.

The problem:
When the user first calls the function, the SDC files config.json, checksums, and results.json are created. Then if the user calls it again the function will assume that the SDC files are part of the user's files and will add them to the results.json and to the checksum folder.

The solution (now):
Before the function add the files to the acro object, it checks if the SDC files exist and deletes them if they are.
```
if "results.json" in os.listdir(path):  # pragma: no cover
         os.remove(f"{path}/results.json")
if "config.json" in os.listdir(path):  # pragma: no cover
        os.remove(f"{path}/config.json")
if "checksums" in os.listdir(path):  # pragma: no cover
        shutil.rmtree(f"{path}/checksums")
```

Do you think there is a better solution?

2023-08-06 16:08 UTC, rpreen commented
Maybe have the user specify both `src` and `dest` paths; and don't worry about what happens in the `dest` in this PR?

In another PR, we need to prompt to ask the user if they are ok with overwriting or changing the `dest` for `finalise()` anyway, so that will then cover this use case?

2023-08-07 14:58 UTC, rpreen requested changes

2023-08-07 14:58 UTC, rpreen commented on acro/record.py
> +                        output.append(Path(os.path.join(root, filename)).name)
This wont work if (a) If the file doesn't exist (b) the file is in a folder in a parent directory (c) what if there are multiple subdirectories which have the same filename - it'll just use the first one found? There is also no warning if any of these things happen, it just doesn't make it to the destination folder.

Actually, I think if the file doesn't exist the current `custom_output()` will just pretend to add the file without actually checking whether it exists so we should fix that here too...

2023-08-08 09:01 UTC, rpreen commented on acro/record.py
> +            logger.info("The file %s doesn't exists", filename)  # pragma: no cover
I think the message should be more explicit:
```python
logger.info("WARNING: Unable to add %s because the file does not exist", filename)
```

Part of me thinks this should be using `warnings.warn()` but then I think it will print the source line in `record.py` which is probably too much info for the researcher here

2023-08-08 10:09 UTC, rpreen approved these changes

2023-08-08 10:11 UTC, merged