Separate Analytic results
AI-SDC/ACRO pull request #46
Opened 2023-03-09 13:35 UTC by mahaalbashir

These changes are related to issue #37 which aims at Separate analytic results out from json files.

2023-03-09 14:56 UTC, jim-smith commented
@mahaalbashir 
1: Looking through the notebook, the formative the regression reports are presented in there is different to how they appear in the first thejson, then in turn ther csv files. 
Could we fix those please.

2: You've got three cases covered by try/except blocks for when you check whether the outputs directory
1.  exists
2. doesn't;t exist but can be created
3. Doesn't;t exist and can't be created

In the last case, should we output a warning to that effect and saying "outputs wil be written to current directory instead" then rest the path accordingly

3. It would be better to use the logger to send messages as warnings to the user (and get stored in a log file) than to just use print() statements which can easily get lost.

2023-03-09 16:23 UTC, rpreen requested changes
Mostly looks good, I've just made some minor suggestions.

2023-03-09 16:23 UTC, rpreen commented on CITATION.cff
> +    orcid: N/A
Please remove the orcid line, if the value is empty then the line is just absent.

2023-03-09 16:23 UTC, rpreen commented on CHANGELOG.md
> +Changes:
Please remove the lines so that the new description falls under the development section at the top.

2023-03-09 16:23 UTC, rpreen commented on acro/utils.py
> +    path = os.path.join(absolute_path, relative_path).replace("\\", "/")
Replacing the slashes (also used in the tests) to make it OS independent feels wrong to me --- wouldn't os.path.normpath or similar be safer for future changes?

2023-03-09 16:23 UTC, rpreen commented on outputs/output_0.csv
> +year,G,N,R,R/G
I think we should remove the generated outputs from this PR and add the outputs folder to the `.gitignore` so we all don't end up accidentally committing them when we run our local tests.

2023-03-09 16:23 UTC, rpreen commented on acro/utils.py
> +        print(f"Directory {OUTPUT_DIRECTORY} created successfully")
Please change the print functions to `logger.info()`. The logger functions should use lazy evaluation so also change the fstring to something like `logger.info("Directory %s created successfully", OUTPUT_DIRECTORY)`

2023-03-10 13:19 UTC, mahaalbashir commented on CHANGELOG.md
> +Changes:
@rpreen Do you mean by that deleting lines 8,9 and 10?

2023-03-10 13:38 UTC, rpreen commented on CHANGELOG.md
> +Changes:
6--10 so it's just underneath the existing "Changes" so we have all the newest changes listed there until we create a new release

2023-03-10 14:29 UTC, rpreen commented on CHANGELOG.md
>  *    .
Can we just remove lines 6 and 7 to clean it up?

2023-03-13 11:52 UTC, rpreen approved these changes
Looks good. Thanks for making the changes.

2023-03-13 11:52 UTC, merged